# elk/filebeat/filebeat.yml

filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log

output.logstash:
  hosts: ["logstash:5044"]

# --- 确保 http 配置块与下面完全一致 ---
http:
  enabled: true
  host: 0.0.0.0
  port: 5066
  prometheus:
    enabled: true
    path: /metrics